config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'

  post 'logout', to: 'sessions#destroy'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first #to be removed later
    if @article.save
      flash[:notice] = "Article was successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted."
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

    def set_article
      @article = Article.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new 
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You have successfully logged in."
      redirect_to user_path(user)
    else
      flash.now[:notice] = "There was something wrong with your login information."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated successfully."
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.username)
  end
end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>

  <% obj.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= truncate(article.description, length: 50) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
      <td>Created by: <%= article.user.username if article.user %></td>
      <td><%= time_ago_in_words(article.created_at) %> ago</td>
      <td>Last updated at: <%= time_ago_in_words(article.updated_at) %> ago</td>

    </tr>
  <% end %>

</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>

  <% end %>

  <%= link_to "Back to articles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit an existing article.</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<p><%= link_to 'Create new article', new_article_path %></p>
<%= will_paginate %>
<%= render 'article', obj: @articles %>
<%= will_paginate %>

app/views/articles/new.html.erb
<h1>Create a new article.</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>

<table>
  <tr>
    <td><%= link_to gravatar_for(@article.user), user_path(@article.user)%></td>
    <td>Created by: <%= link_to @article.user.username, user_path(@article.user)%></td>
    <td><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %><%= %></td>
  </tr>
</table>
<p>Description: <%= @article.description %></p>

<%= link_to "Edit this article", edit_article_path(@article) %><br />
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/messages" %>
    <%= yield %>
    <%= link_to 'Log Out', logout_path, method: :delete %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About.</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Home.</h1>


<%= link_to 'AlphaBlog', articles_path %> |
<%= link_to 'About', about_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<h2>The following errors prevented this from saving:</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>

  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Your Account") %>
  </p>

  <% end %>

  <%= link_to "Back to articles listing", articles_path %>

app/views/users/edit.html.erb
<h1>Edit an Existing User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users.</h1>

<%= will_paginate %>
<table>
  <% @users.each do |user| %>
  <tr>
    <td><%= link_to gravatar_for(user), user_path(user)%></td>
    <td><%= link_to user.username, user_path(user)%><%= %></td>
    <td><%= pluralize(user.articles.count, "article") if user.articles %><%= %></td>
  </tr>
  <% end %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s Page</h1>

<%= gravatar_for @user, size: 150 %>

<h4><%= @user.username%>'s Articles</h4>
<%= will_paginate @user_articles %>
<%= render 'articles/article', obj: @user_articles %>
<%= will_paginate @user_articles %>